[package]
name = "chatoy-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.3"
futures = "0.3.25"

[dependencies.sea-orm]
version = "0.10.5"
features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"]
